Esri/templates-common-library

- package.json
- src/baseClasses/configurationSettingsBase.ts
@rslibed @kellyhutchins Is this the proper logic that we want in here for the `_isWithinConfigurationExperience` function?
> Update _isWithinConfigurationExperience function

- src/baseClasses/ApplicationBase.ts
Add in logic to check euei enabled prop for #7
> Disable GA if eueiEnabled is not set 

- README.md
- src/baseClasses/CompatibilityChecker.ts
- tests/unit/baseClasses/CompatibilityChecker/compatibilityCheckerUT.ts
- tests/unit/baseClasses/all.ts
Refactored logic from Gallery and unit tests
> Compatibility Logic Refactor

- src/baseClasses/CompatibilityChecker.ts
- tests/unit/baseClasses/CompatibilityChecker/compatibilityCheckerUT.ts
Also refactored "await" structure to use Promise.all()
> Added Webscene support to countdown

- src/baseClasses/support/itemUtils.ts
Add logic to handle maps and scenes with no basemap
> update to support maps with no basemap

- src/functionality/a11y.ts
@Csmith246 Once approved and merged, can you republish?
> A11y utils: prefersReducedMotion

- amd/package.json
- esm/package.json
- src/baseClasses/support/itemUtils.ts
Update the selected features logic to load the projection library
> Selected features updates

- amd/package.json
- esm/package.json
- src/baseClasses/ApplicationBase.ts
> v0.0.37 update

- src/functionality/a11y.ts
- src/structuralFunctionality/a11yUtils.ts
> A11y updates

- src/baseClasses/support/configParser.ts
let me know if  you think we should move this logic elsewhere.
> handle search locator deprecation

- amd/package.json
- esm/package.json
- esmBuild.js
Also testing new publish action
> ESM build script update

- src/baseClasses/ApplicationBase.ts
- src/configParamsJSON/nearbyConfigParams.json
- src/interfaces/applicationBase.ts
Made a s light modification to the mixinAllConfigs function and reusing it for the final mixin.
> Fix Nearby config params JSON and properly apply app data values to app

- src/configParamsJSON/sidebarConfigParams.json
Adding support for new measure config options to sidebar
> Sidebar config updates

- src/configParamsJSON/sidebarConfigParams.json
> Decided to not offer a toggle option for coords

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/avConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/chartsConfigParams.json
- src/configParamsJSON/dataSliderConfigParams.json
- src/configParamsJSON/exhibitConfigParams.json
- src/configParamsJSON/insetConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/portfolioConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
Add prop to only show one font for all apps except Countdown
> add singleFont prop to customTheme's config

- src/functionality/search.ts
Shared logic to configure and create search widget
> Search widget creation logic

- src/functionality/search.ts
@kellyhutchins @Csmith246 @bcree11 sorry looks like the build failed due to the imports. Here's a fix for it
> fix imports

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/chartsConfigParams.json
- src/configParamsJSON/countdownConfigParams.json
- src/configParamsJSON/dataSliderConfigParams.json
- src/configParamsJSON/exhibitConfigParams.json
- src/configParamsJSON/insetConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/portfolioConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
https://devtopia.esri.com/webgis/arcgis-portal-app-templates/issues/6877
> update inset positions

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
> Support app fonts

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/avConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/chartsConfigParams.json
- src/configParamsJSON/countdownConfigParams.json
- src/configParamsJSON/dataSliderConfigParams.json
- src/configParamsJSON/exhibitConfigParams.json
- src/configParamsJSON/insetConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/portfolioConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
Doesn't require any changes in apps
> update branding section to logo

- src/configParamsJSON/basicConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/7059
> fix: Remove invalid prop from basic config

- src/configParamsJSON/categoryGalleryConfigParams.json
for https://devtopia.esri.com/webgis/arcgis-template-configuration/issues/1877
> Fix gallery title param

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- Add new widgets to 3d
- Add layer list to lookup and nearby 
- Allow logo scaling
> Add layer list to nearby and lookup

- src/baseClasses/ApplicationBase.ts
When app is embedded in an i frame (but not in config) use popup mode
> fix: oauth in popup when embedded (but not in config)

- src/baseClasses/CompatibilityChecker.ts
- src/configParamsJSON/atlasConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
@Csmith246  what do I need to do to ensure this new app gets added to the EAppTypes?
> Enhancement: Add basic config options for Notify App

- src/structuralFunctionality/telemetry/Alert.tsx
@rslibed this is for the <p> tag issue
> fix: update theme and set html

- src/configParamsJSON/intLegendConfigParams.json
Added infoPanel and infoPanelOpenAtStart to express.
> chore(interactive legend): update config params JSON

- src/configParamsJSON/intLegendConfigParams.json
Header(conditional):
Default value: `true`
Express: `true`
Nested settings:
- Custom header
- Custom header HTML
> chore(interactive legend): updated config params JSON to add conditional header

- amd/package.json
- esm/package.json
- intern.json
- package-lock.json
- src/functionality/generalUtils.ts
- tests/README.md
- tests/unit/all.ts
- tests/unit/baseClasses/CompatibilityChecker/compatibilityCheckerUT.ts
- tests/unit/functionality/GeneralUtils/generalUtilsUT.ts
- tests/unit/functionality/all.ts
> feat: added function for getting Instant Apps Doc Link

- src/configParamsJSON/notifyConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/3590#event-21444010
> fix: Remove unused params

- src/configParamsJSON/imageryViewerConfig.json
update imagery viewer configParams for new theme config
> update Imagery Viewer configParams for new theme config

- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
In progress adding compass option to apps
> feat: Add compass to app config

- src/configParamsJSON/mediaConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/7963
> fix: Hide group layers

- src/configParamsJSON/sidebarConfigParams.json
- src/structuralFunctionality/a11yUtils.ts
I'm not sold on the inputs yet... should we pass in the config value and app item? Or do you think its fine to pull from base? 
I think it should be ok getting the values from base but wanted to see what others thought in case I'm missing anything.
> fix: Add support for generating desc

- src/configParamsJSON/countdownConfigParams.json
- src/configParamsJSON/exhibitConfigParams.json
- src/configParamsJSON/insetConfigParams.json
Will merge once we get the go ahead for R3
> chore: add keyboard shortcuts to apps

- src/configParamsJSON/3dViewerConfigParams.json
> feat: Add basemap gallery to 3d map

- src/configParamsJSON/notifyConfigParams.json
> feat: Add measure to notify

- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/7957#event-22509611
> fix: Update default icon

- src/configParamsJSON/mediaConfigParams.json
Make time settings conditional
> fix: Move time content into conditional

- src/baseClasses/CompatibilityChecker.ts
- src/baseClasses/support/configParamsUtils.ts
- src/configParamsJSON/managerConfigParams.json
@Csmith246  not sure if there is anything else I need to do to add a new app template type? For now I just copied the json from the Basic app but I'll be working on updating it.
> feat: Add Manager

- src/configParamsJSON/intLegendConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
- src/structuralFunctionality/language-switcher/LanguageSwitcher.tsx
- src/structuralFunctionality/language-switcher/support/constants.ts
- src/structuralFunctionality/language-switcher/support/enums.ts
- src/structuralFunctionality/language-switcher/support/interfaces.d.ts
- Add support for 'Language switcher open at start' setting
- Update default icon
- Clean up
> Language switcher updates

- src/configParamsJSON/imageryViewerConfig.json
Adding logo configuration to imagery viewer
> add logo configuration to imageryviewer config

- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/countdownConfigParams.json
- src/configParamsJSON/dataSliderConfigParams.json
- src/configParamsJSON/exhibitConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
talked with Sarah and we decided to remove the group heading for map area
> chore: remove map area group header

- src/structuralFunctionality/telemetry/Alert.tsx
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/8718
> fix: use actions-end slot and add styling for opt in calcite-button

- src/baseClasses/support/itemUtils.ts
- src/configParamsJSON/managerConfigParams.json
Handle manager updates and fix issue #248
> fix: switch to openPopup and manager updates

- src/configParamsJSON/avConfigParams.json
- src/configParamsJSON/chartsConfigParams.json
- src/configParamsJSON/intLegendConfigParams.json
- src/configParamsJSON/portfolioConfigParams.json
Splash setting update for AV, CV, IL and Portfolio
Cover page setting update for CV and Portfolio
> Config Params Updates

- src/baseClasses/CompatibilityChecker.ts
- src/baseClasses/support/configParamsUtils.ts
- src/configParamsJSON/streamflowConfigParams.json
- tests/unit/baseClasses/CompatibilityChecker/compatibilityCheckerUT.ts
Add new template type for the hydro/streamflow viewer app
> feat: Add streamflow template type

- src/baseClasses/CompatibilityChecker.ts
App path changed from hydro to streamflowviewer
> fix: App deployed to streamflowviewer instead of. hydro

- src/structuralFunctionality/language-switcher/LanguageSwitcher.tsx
- src/structuralFunctionality/language-switcher/support/constants.ts
- src/structuralFunctionality/language-switcher/support/interfaces.d.ts
feat: update language switcher helper class to support nested/grouped content
> Language Switcher helper widget class update

- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
Add dual mode config option to apps
> chore: Add  scalebar dual mode to apps

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/dataSliderConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
Should these be set to null instead of ""?
> chore: Remove button text

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
- src/configParamsJSON/streamflowConfigParams.json
Move the position of keyboard shortcuts and add to apps that don't have it 
Change Nearby/Lookup to use landing page not cover page
> Keyboard config updates

- src/configParamsJSON/managerConfigParams.json
> feat: Add floor filter to manager config

- src/structuralFunctionality/language-switcher/LanguageSwitcher.tsx
because of the weird setup in Atlas, it'd help to make private methods publicly available. LMK if you have any concerns
> feat(language-switcher): make private methods public

- src/configParamsJSON/reporterConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/9537
> reporter updates

- src/baseClasses/ApplicationBase.ts
This is a temp update to handle a specific portal error. Need to simplify this logic for r2 and see if we can always just return the details...but it'll need testing
> Portal auth error fix

- src/baseClasses/ApplicationBase.ts
Reverts Esri/templates-common-library#423
> Revert "Portal auth error fix"

- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/functionality/highlight.ts
Update highlight function to support transparency
Add transparent support to Nearby and lookup
> Update highlight function

- src/configParamsJSON/imageryViewerConfig.json
Imagery Viewer Config:
- Added: imageryViewerPosition, imageMeasurementPosition, introductionTitle
> Adi12729/adding introduction title, imageMeasurementPosition and imageryViewerPosition to imagery viewer config

- src/structuralFunctionality/language-switcher/LanguageSwitcher.tsx
- src/structuralFunctionality/language-switcher/support/interfaces.d.ts
- src/structuralFunctionality/language-switcher/support/utils.ts
This PR extracts existing logic into utility functions that apps that do not use the language switcher helper widget class can use
> Extract language switcher logic into separate utils

- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
Remove transparency option from outline and just set for fill
> Update media selection color

- src/configParamsJSON/chartsConfigParams.json
- src/configParamsJSON/intLegendConfigParams.json
chore: add cover page to interactive legend
chore: reorganize chart viewer config params json
> Interactive Legend and Chart Viewer updates

- src/configParamsJSON/lookupConfigParams.json
> feat: Add sketch tool options to Lookup

- src/configParamsJSON/lookupConfigParams.json
Add new lookup options for choosing buffer color
> chore: Add buffer color to lookup

- src/functionality/debounce.ts
- src/functionality/esriWidgetUtils.ts
- src/functionality/positionManager.ts
-Added debounce function
-Added viewInstance param for apps that have multiple views to esriWidgetUtil functions. Default value is 0, so only apps with multiple views are impacted.
> fix: positions in batch to move them one right after the next

- package-lock.json
- package.json
- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/managerConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/notifyConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
- src/configParamsJSON/streamflowConfigParams.json
- src/functionality/esriWidgetUtils.ts
Update to add option to disable feature creation in Manager
> fix: Add option to disable feature creation

- src/configParamsJSON/intLegendConfigParams.json
chore: Move cover page to subsection. Group non-cover page settings in About to 'App details' subsection.
> Interactive Legend: Move cover page to it's own subsection

- src/configParamsJSON/reporterConfigParams.json
- src/functionality/configUtils.ts
- src/interfaces/commonInterfaces.ts
- get logo and link params based on customTheme and applySharedTheme
- apply token when needed 
- Update ICustomTheme interface
> chore: add getLogoOptions

- amd/package.json
- esm/package.json
- package-lock.json
- src/functionality/esriWidgetUtils.ts
- Add ability to add legend to layerList
> chore: layer-list update

- src/configParamsJSON/sidebarConfigParams.json
Add ability for users to define custom label text for sidebar action bar tools
> feat: Add ability to update tool labels in side panel

- src/configParamsJSON/3dViewerConfigParams.json
Add oriented imagery config option to 3D Viewer
> feat: Add oriented imagery to 3d config

- src/configParamsJSON/notifyConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4766
> update notify settings

- src/structuralFunctionality/language-switcher/support/constants.ts
Note: The strings in this change are not meant to be translated and are intended to be hard-coded strings.
> chore: add language data obj

- src/configParamsJSON/3dViewerConfigParams.json
- src/configParamsJSON/atlasConfigParams.json
- src/configParamsJSON/avConfigParams.json
- src/configParamsJSON/basicConfigParams.json
- src/configParamsJSON/compareConfigParams.json
- src/configParamsJSON/countdownConfigParams.json
- src/configParamsJSON/dataSliderConfigParams.json
- src/configParamsJSON/exhibitConfigParams.json
- src/configParamsJSON/insetConfigParams.json
- src/configParamsJSON/intLegendConfigParams.json
- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/mediaConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
- src/configParamsJSON/observerConfigParams.json
- src/configParamsJSON/portfolioConfigParams.json
- src/configParamsJSON/reporterConfigParams.json
- src/configParamsJSON/sidebarConfigParams.json
Move language switcher into express for increased visibility
> chore: Move out of express

- src/configParamsJSON/managerConfigParams.json
##Summary
Provide a configuration option for the informational text to the left of the main table view
> feat: add new option to Manager config

- src/configParamsJSON/notifyConfigParams.json
https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/4766
> update notify options

- src/functionality/esriWidgetUtils.ts
- src/interfaces/languageSwitcherInterfaces.ts
- src/structuralFunctionality/language-switcher/support/utils.ts
- add function that takes any type of variable and updates it based on the t9n file
> chore: add translations helpers

- src/configParamsJSON/streamflowConfigParams.json
Add new config option for specifying the hydro model to use
> chore: Add new section and config model option

- src/configParamsJSON/lookupConfigParams.json
> feat: Add config option for enable/disable one click search

- src/configParamsJSON/avConfigParams.json
- src/configParamsJSON/chartsConfigParams.json
- src/configParamsJSON/intLegendConfigParams.json
- src/configParamsJSON/observerConfigParams.json
- src/configParamsJSON/portfolioConfigParams.json
Added to AV, CV, IL, Observer, and Portfolio
> Config ParamsJSON: visibilityIcon

- src/functionality/esriWidgetUtils.ts
Remove aspects that were more specific to the implementation from the 3d Viewer app
> refactor: make Building Explorer function more generic

- src/configParamsJSON/generalConfigParams.ts
Updated the Config JSON too include common tools from other apps.
Config based on wireframes - https://www.figma.com/design/yzAXsPeym0aGY0T58dgzti/General-App?node-id=0-1&p=f&t=3bYbdPYa3hNudxKr-0
> Update General App Config JSON

- src/configParamsJSON/3dViewerConfigParams.ts
- src/configParamsJSON/basicConfigParams.ts
- src/configParamsJSON/dataSliderConfigParams.ts
- src/configParamsJSON/intLegendConfigParams.ts
- src/configParamsJSON/mediaConfigParams.ts
- src/configParamsJSON/sidebarConfigParams.ts
I removed the screenshot configuration from the app json files.
I did not remove screenshot in Nearby or Zone Lookup config.
> Remove Screenshot Config

- src/configParamsJSON/lookupConfigParams.ts
- src/configParamsJSON/nearbyConfigParams.ts
remove screenshot tool from nearby and lookup
> remove screenshot

- src/configParamsJSON/mediaConfigParams.ts
> swipe - Update mediaConfigParams.ts

- src/configParamsJSON/compareConfigParams.ts
- src/configParamsJSON/exhibitConfigParams.ts
- src/configParamsJSON/insetConfigParams.ts
- src/configParamsJSON/portfolioConfigParams.ts
- src/configParamsJSON/reporterConfigParams.ts
This update will show the introduction window title setting in express for Portfolio, Insets, Exhibit, Compare, and Reporter. https://devtopia.esri.com/WebGIS/arcgis-template-configuration/issues/5217
> Update Intro window title to express

- src/configParamsJSON/portfolioConfigParams.ts
Discussed with @sarahmcdonald7 and we decided that it'd be best to ensure that tabbed and accordion portfolio apps maintain the header since those 2 layouts are more commonly used than carousel.
> chore: update header defaultValue to true

- amd/package.json
- esm/package.json
- src/baseClasses/ApplicationBase.ts
Implementation in AppBase that would work for all apps:
> feat: portal banner

- src/configParamsJSON/insetConfigParams.ts
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/11712#event-27955226
> chore: remove languageSwitcherPosition. LS is in header so it's not needed.

- src/configParamsJSON/reporterConfigParams.ts
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/11737
> chore: add highlight settings

- src/functionality/esriWidgetUtils.ts
- src/structuralFunctionality/widgets/slice/SlicePanel.tsx
- src/structuralFunctionality/widgets/viewshed/ViewshedPanel.tsx
**June 2025**
* Add the Line of Sight, Shadow Cast, and Viewshed tools to the widget utilities so it can be used in multiple Instant Apps
* Update the Floor Filter tool to adhere with the conventions from the other 3D tools
> feat: add Line of Sight, Shadow Cast, Viewshed to the library; update Floor Filter

- src/configParamsJSON/managerConfigParams.ts
Enable the setting governing on/off layer toggling for each attached map
> feat(manager): Enable layer visibility selection setting

- src/configParamsJSON/basicConfigParams.ts
- src/configParamsJSON/lookupConfigParams.ts
- src/configParamsJSON/nearbyConfigParams.ts
Move all media settings to basic. We know this changes a few defaults but we are ok with that
> chore: Add all media settings to basic

- src/configParamsJSON/streamflowConfigParams.ts
Removing the option to filter streams by flow for this release.
> chore: Remove streamflow filter option

- src/configParamsJSON/webEditorConfigParams.ts
This PR addresses the required updates to the WebEditor configuration params.
> update web editor config params

- src/configParamsJSON/imageryViewerConfig.ts
Added visibility icon for layerlist for imagery-viewer
> add layerlist visibilityicon config to imagery-viewer

- src/configParamsJSON/galleryConfigParams.ts
Remove support for custom HTML headers in the app
> chore: remove the custom header setting from the Gallery app

- src/configParamsJSON/webEditorConfigParams.ts
Adding another tweak to the config params for Web Editor
> update WE config params

- src/baseClasses/CompatibilityChecker.ts
Indicates that Gallery is compatible with Group Resources
> fix: Gallery app group compatibility

- src/configParamsJSON/webEditorConfigParams.ts
Updates for the express version of Web Editor and remove `enableUserControlSnappingGeomertyFeaures`
> update WE editing config for express

- src/configParamsJSON/sidebarConfigParams.ts
Reordered the intro window configuration settings to list title, content, button text, then icon. 
Updated JSON property format to use " " .
> Reordered Intro window settings for Sidebar 

- src/functionality/search.ts
> fix(search): prevent passing in PopupTemplate class into fromJSON
