- src/configParamsJSON/basicConfigParams.json
Basic only has support for a few widgets so it was fairly straightforward to add in appfont support
> Add in support for appFonts for basic

- src/baseClasses/ApplicationBase.ts
The issue was that an "undefined" value was getting type coerced into a string, and then the full string "undefined/sharing/rest/info" was resolving with a `200` code from the fetch request for whatever reason
> Fix for issue with local testing

- src/structuralFunctionality/telemetry/telemetry.ts
Issue reported on Esri community where GA is disabled but the opt-in message still appears. Looks like we need to check to ensure GA or AA are enabled before showing consent. Here's the community thread: 
https://community.esri.com/t5/arcgis-instant-apps-questions/quot-opt-in-quot-message-at-the-bottom-of-embedded/m-p/1230790#M1473
@Csmith246  I tested with Google but don't have Adobe credentials. Can you test this one next week and verify this update is ok for both and then we can merge. No hurry because there is a workaround
> fix: consent message appears when GA isn't enabled

- src/functionality/configUtils.ts
When updating the mode to "light" or "dark" in the config panel, the view's calcite-mode class isn't being updated so added a helper function to replace the current class mode.
view's calcite-mode class isn't updated which could cause theme issues in preview window's UI if the view has any custom widgets that use  calcite components:
> feat: add a way to update the view's calcite-mode class

- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
Remove the unsupported table option from these apps
> fix: remove table option from nearby/lookup

- src/structuralFunctionality/a11yUtils.ts
Added a function that checks to see if prefers reduced motion is enabled and if so it disables it for goTo. Can be used as the goToOverride function for popup and search. Here's a sample showing how its set for the popup and search widgets. 
https://codepen.io/kellyhutchins/pen/bGxqWwg?editors=0010
> feat: Add goToOverrides function that detects prefers-reduced-motion

- package-lock.json
- package.json
One of the updates in the imagery layer function requires 4.26 and I forgot to install package-lock. Here's the update
> fix: Ensure API is updated to 4.26 so highlight option is available

- src/functionality/search.ts
This update checks for the `en` string `Find address or place`, and replaces the search widget's allPlaceholder property with the translated allPlaceholder string.
> createSearch fix

- src/configParamsJSON/managerConfigParams.json
The config for manager shouldn't allow for positioning the widgets.
> fix: Remove unused position prop

- src/structuralFunctionality/language-switcher/LanguageSwitcher.tsx
- src/structuralFunctionality/language-switcher/support/constants.ts
This fix prevents non-string and non-translatable values to be overwritten when using the language switcher.
> fix: language switcher overwrite logic

- src/structuralFunctionality/landing-page/LandingPage.tsx
- src/structuralFunctionality/landing-page/README.md
@kellyhutchins with this update you'll just need to base in the app base
for example:
```
new LandingPage({
base: this.base,
container: document.createElement("div"),
configurationSettings: this._appConfig,
handles: this._handles,
portal: this.base.portal
});
```
> Handle deprecated cover page settings

- src/configParamsJSON/reporterConfigParams.json
FYI @bcree11  we are removing this because the app is beta and if there are late translations etc things could get weird.
> fix: Remove language switcher from beta app

- src/configParamsJSON/streamflowConfigParams.json
Update. location of help panel in streamflow
> fix: Move help panel to upper left corner

- src/configParamsJSON/sidebarConfigParams.json
Updated to add transparent support to Sidebar. @brandon there is an enhancement to add to Insets too. Transparency could work for this or we could enhance the config to allow for no-color too.
> feat: Add transparent support to sidebar

- src/configParamsJSON/lookupConfigParams.json
- src/configParamsJSON/nearbyConfigParams.json
Removing this option since they'll get related records by default now.
> chore: Remove related records from Nearby Lookup

- src/configParamsJSON/basicConfigParams.json
Add new option to support link charts in one app for Enterprise 11.5
> chore: Add link chart support to Basic

- src/functionality/esriWidgetUtils.ts
Add the Building Explorer tool to the widget utilities so it can be used in multiple Instant Apps.
* Replaced the `addBuildingExplorer(...)` call from the widget utils in 3D Viewer with a call to the function of the same name within TCL
* Confirmed the Building Explorer functioned as expected
* Confirmed the tool location changes as expected when modified via the position manager
> feat: add the Building Explorer tool to the library

- src/functionality/esriWidgetUtils.ts
Add the Weather tool to the widget utilities so it can be used in multiple Instant Apps.
This is an updated version of #592 with the latest from the dev branch
* Replaced the `addWeather(...)` call from the widget utils in 3D Viewer with a call to the function of the same name within TCL
* Confirmed the Weather functioned as expected
* Confirmed the tool location changes as expected when modified via the position manager
> feat: add the Weather tool to the library

- src/functionality/esriWidgetUtils.ts
Add the Daylight tool to the widget utilities so it can be used in multiple Instant Apps.
* Replaced the `addDaylight(...)` call from the widget utils in 3D Viewer with a call to the function of the same name within TCL
* Confirmed the Daylight functioned as expected
* Confirmed the tool location changes as expected when modified via the position manager
> feat: integrate the Daylight tool

- src/functionality/esriWidgetUtils.ts
Keys object allows for different naming of the props across apps
> feat: enforce deprecated widget Prop rules

- src/functionality/esriWidgetUtils.ts
Since @JoeRodriguez-136 confirms all templates use same keys for the props
> chore: remove key flexibility in handleDeprecatedProps

- src/functionality/esriWidgetUtils.ts
Makes sure that screenshot won't show, even if old code for its instantiation still exists in a template
> fix: explicitly set `screenshot` to false

- src/functionality/esriWidgetUtils.ts
- src/structuralFunctionality/widgets/slice/SlicePanel.tsx
**June 2025**
Add the Slice tool to the widget utilities so it can be used in multiple Instant Apps.
* Replaced the `addSlice(...)` call from the widget utils in 3D Viewer with a call to the function of the same name within TCL
* Confirmed the Slice functioned as expected
* Confirmed the tool location changes as expected when modified via the position manager
Copied from #598
> feat: add the Slice tool to the library

- src/configParamsJSON/managerConfigParams.ts
Adds an option on the Manager config to control feature selection (`multiple` or `single`)
> feat: add feature selection mode setting for Manager

- src/configParamsJSON/managerConfigParams.ts
Moved the feature selection tool and export to CSV tool to different subsections.
Feature Selection tool should now be in the modify subsection.
Export to CSV tool should be in share subsection.
> Move feature selection and export to CSV settings in Manager app

- src/functionality/highlight.ts
highlightOptions is deprecated: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#highlightOptions
Updated to using highlights collection and updating "default" highlightOption in it.
> chore: update deprecated prop

- src/configParamsJSON/managerConfigParams.ts
We will add a new section **Layer Options** to the config along with a corresponding setting. This change renames the **Table Options** setting `layerOptions` -> `tableOptions` to avoid confusion
> chore(manager): rename setting in prep for new Layer Options setting

- src/functionality/esriWidgetUtils.ts
Recent changes to the `addFloorFilter` utility were causing errors in the Reporter app.  This commit rolls back those changes to restore functionality and allow time for a different approach
> fix: rollback changes to floor filter tool causing Reporter errors

- src/functionality/esriWidgetUtils.ts
- src/functionality/search.ts
Problem:
Apps that use `createSearch` are unable to leverage the `search-complete` callback logic because it currently resides within `addSearch`.
Solution:
Refactor the code by relocating the `search-complete` callback logic from `addSearch` to `createSearch`. This change ensures that `createSearch` and `addSearch` (calls `createSearch`) can both use the `search-complete` callback functionality.
> fix(search): move search-complete logic to createSearch

- src/configParamsJSON/galleryConfigParams.ts
Add a new configuration setting to support a radio button control for `useOrgCategories` instead of the default switch control. 
Also, not sure why I set "group" as the default value when it should be a boolean `¯\_(ツ)_/¯`
> chore(gallery): add new config value for useOrgCategories
